#!/bin/bash


function apply_theme() {
    set_env_var "THEME" "$1"
    sudo echo -n
    comango upgrade -l
    xmonad --recompile &> /dev/null
    xmonad --restart &> /dev/null
    comango hook reload
}

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"


function set_theme() {
    case "$1" in
        1|light)   apply_theme "light-pink" ;;
        2|dark)    apply_theme "dark-cyan"  ;;
        3|horizon) apply_theme "horizon"    ;;

        *)         echo "unknown theme"   ;;
    esac
}



if [ -z "$1" ]; then
    echo "1  light"
    echo "2  dark"
    echo "3  horizon"
    read -p "pick a theme: " selection
    set_theme $selection
else
    set_theme "$@"
fi

