#!/bin/bash


BLACK='181a20'
LIGHT_GRAY='eeeeee'
DARK_GRAY='4a4a4a'
WHITE='ffffff'


D_RED='cc0000'
D_GREEN='00aa00'
D_YELLOW='bb8800'
D_BLUE='0000cc'
D_MAGENTA='cc00cc'
D_CYAN='00cccc'
D_ORANGE='0932b0'

L_RED='f07178'
L_GREEN='c3e88d'
L_YELLOW='ffcb6b'
L_BLUE='82aaff'
L_MAGENTA='c792ea'
L_CYAN='89ddff'
L_ORANGE='fab387'

case $THEME in
  dark-cyan)
    LIGHT_GRAY='999999'

    RED=$L_RED
    GREEN=$L_GREEN
    YELLOW=$L_YELLOW
    BLUE=$L_BLUE
    MAGENTA=$L_MAGENTA
    CYAN=$L_CYAN
    ORANGE=$L_ORANGE

    BACKGROUND=$BLACK
    BACKGROUND_ALT=$DARK_GRAY
    FOREGROUND=$WHITE
    FOREGROUND_ALT=$LIGHT_GRAY
    PRIMARY=$L_CYAN
    SECONDARY=$MAGENTA
    ALERT=$RED
    DARK_THEME=true
    GTK_THEME=Adwaita-dark

    BAR_OPACITY=aa
    TERM_OPACITY=.80
    ;;
  light-pink)
    RED=$D_RED
    GREEN=$D_GREEN
    YELLOW=$D_YELLOW
    BLUE=$D_BLUE
    MAGENTA=$D_MAGENTA
    CYAN=$D_CYAN
    ORANGE=$D_ORANGE

    BACKGROUND=$WHITE
    BACKGROUND_ALT=$LIGHT_GRAY
    FOREGROUND=$BLACK
    FOREGROUND_ALT=$DARK_GRAY
    PRIMARY=$L_RED
    SECONDARY=$MAGENTA
    ALERT=ff0000
    DARK_THEME=false
    GTK_THEME=Adwaita

    BAR_OPACITY=00
    TERM_OPACITY=.80
    ;;
  pink-dreams)
    RED=$D_RED
    GREEN=$D_GREEN
    YELLOW=$D_YELLOW
    BLUE=$D_BLUE
    MAGENTA=$D_MAGENTA
    CYAN=$D_CYAN
    ORANGE=$D_ORANGE

    BACKGROUND=$WHITE
    BACKGROUND_ALT=$LIGHT_GRAY
    FOREGROUND=$BLACK
    FOREGROUND_ALT=$DARK_GRAY
    PRIMARY=ff919e
    SECONDARY=$MAGENTA
    ALERT=ff0000
    DARK_THEME=false
    GTK_THEME=Adwaita

    BAR_OPACITY=33
    TERM_OPACITY=.80


    ;;
  horizon)
    LIGHT_GRAY='999999'

    RED=D4516f
    GREEN=FAC29A
    YELLOW=F09383
    BLUE=$L_BLUE
    MAGENTA=B877DB
    CYAN=1D8991
    ORANGE=$L_ORANGE

    BACKGROUND=232530
    BACKGROUND_ALT=474A60
    FOREGROUND=F9DDDD
    FOREGROUND_ALT=$LIGHT_GRAY
    PRIMARY=$CYAN
    SECONDARY=$RED
    ALERT=$RED
    DARK_THEME=true
    GTK_THEME=Adwaita-dark

    BAR_OPACITY=ff
    TERM_OPACITY=.80
    ;;
  catppuccin-pink-dark)
    LIGHT_GRAY='f5e0dc'

    RED='f38ba8'
    GREEN='a6e3a1'
    YELLOW='f9e2af'
    BLUE='89b4fa'
    MAGENTA='F5C2E7'
    CYAN='94e2d5'
    ORANGE='fab387'

    BACKGROUND='11111b'
    BACKGROUND_ALT='585B70'
    FOREGROUND='cdd6f4'
    FOREGROUND_ALT='A6ADC8'
    PRIMARY='f5c2e7'
    SECONDARY='fab387'
    ALERT='f38ba8'
    DARK_THEME=true
    GTK_THEME='Catppuccin-Mocha-Standard-Pink-Dark'

    BAR_OPACITY=aa
    TERM_OPACITY=.80
    ;;
  *)
    echo "THEME="$THEME" unknown or not set"
    exit 1
esac

BAR_OPACITY_PCT=$(awk "BEGIN { print $(printf "%.2f" "0x$BAR_OPACITY") / 255}")
BAR_COLOR_RGBA=$(printf "rgba(%d,%d,%d,%.2f)" 0x${BACKGROUND:0:2} 0x${BACKGROUND:2:2} 0x${BACKGROUND:4:2} $BAR_OPACITY_PCT)
